### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-KyCodeHuynh#4]
#### As a user I want to be prevented from submitting invalid image URLs.

Acceptance criteria:
- [x] I cannot successfully save an image with an invalid URL.
- [x] An error message is associated with the appropriate input field on
  failure.

Discussion Topic:
- [x] What is a valid image URL?

Dependencies:
- Save Image Link

**Comment by KyCodeHuynh** [comment]
Because I currently use the [`url_field`](http://guides.rubyonrails.org/form_helpers.html#other-helpers-of-interest) helper, some URL validation is already included for free:

![screen shot 2016-06-17 at 4 44 39 pm](https://cloud.githubusercontent.com/assets/4713937/16167531/f69ea83c-34aa-11e6-9a3f-b933098a0e13.png)

However, this is rather cheating, as:

* We'd normally use something like [`flash`](http://api.rubyonrails.org/classes/ActionDispatch/Flash.html)
* These may be valid URLs, but not necessarily ones that point to images. I am not sure of an easy way to address this short of writing my own regular expression. 
* "Please enter a URL" is a not a helpful copy message. What if someone doesn't know what a "URL" is? It'd be better to list examples in the error message.

NOTE: failing to have the protocol does indeed invalidate URLs. For example: 

```
<img width="400" src="tsc.oit.gatech.edu/sites/default/files/demo2015/microsoft-logo.jpg" alt="Microsoft logo">
```

will give a broken image icon. We need the `http://` prefix.

**Comment by KyCodeHuynh** [comment]
## Image Validation Options

_The below is in-progress_

After discussion with Daniel, I've identified two ways of validating image URLs: 

1. A regular expression
2. Executing an [HTTP HEAD](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4) request for each URL and checking the [`Content-Type`](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) header for `JPEG`, `GIF`, or `PNG`.

I discuss the pros/cons of each below and explain why I ultimately chose to use a regular expression instead. 


### Using a Regular Expression

#### Pros

* Fast
* No additional latency from waiting on network operations to complete


#### Cons

* Full test coverage is essential 
* As evidenced by the problem of [validating URLs in general](https://mathiasbynens.be/demo/url-regex) (a harder problem than this limited subset), we can't hope to catch everything.


### Using an HTTP HEAD Request

An option that our discussion quickly discarded was downloading the whole image and checking the [magic number at the start of it](https://stackoverflow.com/questions/676949/best-way-to-determine-if-a-url-is-an-image-in-php). While that is the most definitive way to check the actual type of a file (assuming it is non-malicious and not pulling off some masquerade), this would take far too long. A full download would also be superfluous if all we want to do eventually is just store the image link. 

How can we tell apart a popularly shared image vs. a reflected DDoS attack using us for amplification? 

Much of these concerns go away if we download the images and host them ourselves but that introduces: 

* Copyright concerns. While immune from liability, we only maintain that immunity while we actively police user-submitted content as we receive DMCA reports. The more popular we become, the bigger of a financial target we are for lawsuits, as with Google v. Viacom. 
* Scaling difficulties. EverPix is an example of a service that was overwhelmed by its storage costs
